name: Build the Nix packages

on:
  pull_request:
    paths-ignore:
      - 'README.*'

  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build with Nix on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        package:
          - default
          - firefox
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build the Nix packages
        run: |
          nix build ".#${PACKAGE}" -L
        env:
          PACKAGE: ${{ matrix.package }}
